### ISSUE TITLE
Unable to disassemble ship

### ISSUE THREAD

**Issue by aD-1337** [ValkyrienSkies/Eureka#91] opened 2023-01-09 18:52 UTC
You cannot unbind a ship through the ship helm menu

**Comment by walksanatora** [comment] 2023-01-10 16:58
this question makes no sense
do you mean that you cannot *disassemble* a ship
if you mean disassemble it is a config option (disabled by default)

**Comment by copperwarrior** [comment] 2023-01-15 15:11
Duplicate of #34

**Closed as completed by copperwarrior** 2023-01-15 15:11 UTC
Labels: duplicate
