### ISSUE TITLE
minecraft:snow_block  and possible minecraft:light need to be added to the blocklist

### ISSUE THREAD

**Issue by spottenn** [ValkyrienSkies/Eureka#248] opened 2023-08-22 08:25 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Fabric

### Issue description

When in snowy slopes and similar, if your ship accidentally touches a snow block and you hit asssembly, all the connected snow blocks also get assembled into the ship. We accidentally made a giant mountain range sized ship with this. I'm a developer and I looked through the code, The correct file to add it to is "Eureka/common/src/main/kotlin/org/valkyrienskies/eureka
/EurekaConfig.kt"

Also, the light block should probably be added because the user doesn't expect the ship to include light blocks and our shipping was touching the snow blocks via a light block.

### Issue reproduction

Go to any biome with many adjacent snow blocks (not just snow, but full snow blocks) and stick a helm on one of blocks and look at the hitbox size of the ship (f3+b).

**Comment by NullHarp** [comment] 2023-08-22 20:09
technically not a bug, just not a desirable outcome, you can add snow manually to the blacklist by editing the config

**Comment by NullHarp** [comment] 2023-08-22 20:09
also light cant be assembled

**Comment by millennIumAMbiguity** [comment] 2023-08-24 12:44
Since Snow is available in all versions, the blacklist would need to be updated on all versions. Since 1.20 is behind 1.19, as long as snow is added to 1.16, 1.18, and 1.19; all versions will In the future have the correct blacklist.

You said that you are a developer yourself, feel free to make a pull request.

**Comment by millennIumAMbiguity** [comment] 2023-10-11 18:50
merged to main

**Closed as completed by millennIumAMbiguity** 2023-10-11 18:50 UTC
Labels: bug, Blacklist
