### ISSUE TITLE
disassemble issues<title>

### ISSUE THREAD

**Issue by CurryMaster911** [ValkyrienSkies/Eureka#306] opened 2024-02-15 12:25 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

### Issue description

when you disassemble ship, steering wheel flips, fences connect to air , chests don't render properly and rails break

### Issue reproduction

create a ship with fences chests and rails.

### Logs

[15Feb2024 12:04:29.195] [Server thread/ERROR] [VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big! AABB[-2.8669942650000006E7, 64.31822074451146, -167.074393345996] -> [-65.70718576874104, 66.30000001192093, 1.2290063650000006E7] returning empty list! this might break things
--
524 | [15Feb2024 12:04:34.200] [Server thread/ERROR] [VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big! AABB[-2.8669942650000006E7, 64.39465154155872, -170.41995884039005] -> [-59.40395370086376, 66.30000001192093, 1.2290063650000006E7] returning empty list! this might break things
525 | [15Feb2024 12:04:39.220] [Server thread/ERROR] [VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big! AABB[-2.8669942650000006E7, 65.26685333764654, -177.26604922115803] -> [-61.21737164631486, 67.06685328996282, 1.2290063650000006E7] returning empty list! this might break things
526 | [15Feb2024 12:04:44.249] [Server thread/ERROR] [VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big! AABB[-2.8669942650000006E7, 66.0, -180.234512925148] -> [-61.46339210495353, 68.18558294073061, 1.2290063650000006E7] returning empty list! this might break things
527 | [15Feb2024 12:04:49.405] [Server thread/ERROR] [VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big! AABB[-2.8669942650000006E7, 66.0, -180.1960947662592] -> [-61.44349114410579, 67.8131251628835, 1.2290063650000006E7] returning empty list! this might break things

**Comment by millennIumAMbiguity** [comment] 2024-04-17 17:32
Duplicate of #185

**Closed as not planned by millennIumAMbiguity** 2024-04-17 17:32 UTC
Labels: bug, duplicate
