### ISSUE TITLE
Check-in on Progress for Minecraft 1.21 Update

### ISSUE THREAD

**Issue by Mist-EXE** [ValkyrienSkies/Eureka#390] opened 2024-08-01 21:51 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Eureka version

newest one

### VS2 version

newest one

### Mod Loader

Forge

### Issue description

Inquiry: Update for Minecraft 1.21 

Hi Eureka Ships Team, I hope this message finds you well. I am a big fan of the Eureka Ships mod and have been enjoying it immensely in Minecraft 1.20.1. With the recent release of Minecraft 1.21, I was wondering if there are any plans or progress on updating the mod to support the latest version. I understand that updating mods takes time and effort, and I appreciate all the hard work you put into maintaining and improving the mod. Any information regarding the update timeline or current status would be greatly appreciated. Thank you!

Best regards, Mist-EXE

### Issue reproduction

Have a nice day Eureka Devs :)

**Comment by ewoudje** [comment] 2024-08-01 22:50
This is not a bug, so im closing this. 

We will eventually update to 1.21, but this version has only been out for a month? 
So not immediately no. And there is no ETA, we will make it when we have time and motivation for it.

**Closed as completed by ewoudje** 2024-08-01 22:50 UTC
Labels: bug

**Comment by Mist-EXE** [comment] 2024-08-02 20:14
yeah just asking, no pressure or anything!
