### ISSUE TITLE
Storage Drawers items not visible (1.20.1 no shaders active)

### ISSUE THREAD

**Issue by PumaBlack** [ValkyrienSkies/Eureka#268] opened 2023-10-22 05:22 UTC
### Mod Name

Storage Drawers Mod (Owner: Texelsaur)

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Minecraft Version is **1.20.1**  (I could not choose it from the dropdown)

The Items in the StorageDrawers are not rendered on the drawer-blocks on assembles Ships. They are stored inside (the upgrades as well), but not visible. The drawers look empty. No Item, no fillbar, no counter.

I can take and store items as usual, but nothing is rendered.

### Issue reproduction

Just assemble a ship and place a drawer, no matter if the drawer was placed before or after assembling

**Comment by millennIumAMbiguity** [comment] 2023-11-04 01:28
duplicate of #159

**Closed as completed by millennIumAMbiguity** 2023-11-04 01:28 UTC
Labels: compat
