### ISSUE TITLE
game fails to start when quark is installed

### ISSUE THREAD

**Issue by drmilk240** [ValkyrienSkies/Eureka#48] opened 2022-11-21 21:42 UTC
In version alpha5 of Eureka, installing quark will make the game briefly start, and then close instantly, but it doesn't register as a crash and nothing shows up in logs.

Quark is obviously a very useful mod, and would be infinitely helpful to have installed alongside Eureka.

**Comment by Rubydesic** [comment] 2022-11-21 23:03
duplicate of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/205

**Closed by Rubydesic** 2022-11-21 23:03 UTC
