### ISSUE TITLE
Invisible Ship

### ISSUE THREAD

**Issue by enderfree** [ValkyrienSkies/Eureka#145] opened 2023-02-08 15:24 UTC
Sorry for the duplicate, but I can't find the old issue. I looked in my mods because you seem to have been thinking it came from an imcompatibility with an other mod, and as you suspected, it does. It seem to be an incompatibility with Immersive Portals.

**Comment by ThePlasticPotato** [comment] 2023-02-08 15:42
Immersive Portals isn’t compatible for now, so yeah. It’s known-

**Comment by Rubydesic** [comment] 2023-02-08 19:22
Duplicate of #77

**Closed as completed by Rubydesic** 2023-02-08 19:22 UTC
