### ISSUE TITLE
Disassembling to the right of original orientation makes blocks like stairs and fences rotate (and how to fix the ship in such event)

### ISSUE THREAD

**Issue by Ramelstag** [ValkyrienSkies/Eureka#193] opened 2023-05-11 01:32 UTC
I've been testing this for a while now, and I'm very confident I have found out what causes this bug.
**_If you assemble your vessel, when it's pointing, for example, NORTH, and then at some point disassemble pointing EAST (90° to the right/clockwise)_** causes stairs, trapdoors, fences, doors, chests, beds and many other blocks with orientations to rotate and ruin your vessel. 
**_And, fortunately, re-assembling and then disassembling to the next right-most direction (NORTH again in that example, because the helm will also rotate), the ship will fix itself._** 
Disassembling to any other direction except the one 90° to the right of the original position is fine. I even made a full 360° rotation, disassembling and assembling every 90°, but, going to the left, and it didn't bug out. The opposite causes it to bug out, and then fix itself on the next disassembly, repeatedly.
At first I thought corner stairs were causing it, so I designed my airship without these, but it still happened. Good thing I had a schematic. 
I hope this post helps someone else out there.

**Comment by millennIumAMbiguity** [comment] 2024-04-17 17:29
Duplicate of #185

**Closed as not planned by millennIumAMbiguity** 2024-04-17 17:29 UTC
Labels: bug, duplicate
