### ISSUE TITLE
Anchor problem

### ISSUE THREAD

**Issue by Deno-V** [ValkyrienSkies/Eureka#342] opened 2024-04-26 14:32 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Fabric

### Issue description

 When an anchor is placed and has been activated, the ship can not be moved. However if I deactivate the red stone signal later, the ship still stuck, it won't move. If I destroy the control block, the whole ship will behave strange. And I can not use the assemble align function either.

### Issue reproduction

I have installed continuity clockwork and create mods. Minecraft version is 1.20.1 with fabric installed.

**Comment by millennIumAMbiguity** [comment] 2024-04-26 14:52
Duplicate of #279

**Closed as not planned by millennIumAMbiguity** 2024-04-26 14:52 UTC
Labels: bug, duplicate
