### ISSUE TITLE
Rain goes straight through boats

### ISSUE THREAD

**Issue by MaxIsBoring** [ValkyrienSkies/Eureka#383] opened 2024-06-28 17:04 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Eureka version

eureka-1201-1.5.1-beta.3

### Mod Loader

Forge

### Issue description

![2024-06-28_12 56 21](https://github.com/ValkyrienSkies/Eureka/assets/142853292/63ce2af3-dfbe-4121-b5bc-5e634ba5dfc0)
When you assemble a boat and its raining the rain will go straight through your boat, I'm not sure this is a compatibility nor a version thing, I'm sorry if this is a problem on my side or if you have gotten these a lot.

### Issue reproduction

Assemble ship and let it rain.

**Comment by CoderModeGit** [comment] 2024-07-01 14:47
Duplicate of [#184 ](https://github.com/ValkyrienSkies/Eureka/issues/184)

**Comment by ewoudje** [comment] 2024-08-01 22:55
Closing in favor of https://github.com/ValkyrienSkies/Eureka/issues/184

**Closed as completed by ewoudje** 2024-08-01 22:55 UTC
Labels: bug
