### ISSUE TITLE
Helm applies weird inertia

### ISSUE THREAD

**Issue by Amzd** [ValkyrienSkies/Eureka#324] opened 2024-04-02 08:54 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Fabric

### Issue description

I would like a boat that feels a bit more heavy but when you get on the helm, all boats basically feel the same. They accelerate and decelerate basically instantly when you press/release keys.

Quick solution might be to only take over the physics when a player is actually controlling. This means releasing W wouldn't instantly stop the boat.

https://github.com/ValkyrienSkies/Eureka/blob/156760618f7a6b17534ec130fd89fb768f77caaf/common/src/main/kotlin/org/valkyrienskies/eureka/ship/EurekaShipControl.kt#L171
```diff
-        if(player != null) {
+        // Only care about player with inputs
+        val hasInputs = player != null && (player.forwardImpulse != 0.0f || player.leftImpulse != 0.0f || player.upImpulse != 0.0f || player.sprintOn || player.cruise)
+        if (hasInputs) {
```

A better solution would be to take inertia into account instead of the WASD of the helm completely overriding any prior inertia.

### Issue reproduction

on a helm while holding W:
release W: boat stops instantly
get off helm: boat stops after inertia runs out

**Comment by PriestOfFern** [comment] 2024-04-02 15:57
This isn't a bug

**Comment by Amzd** [comment] 2024-04-05 08:59
Hmm okay, not sure why this is the intended way but fine. Then this issue is a feature request.

**Comment by millennIumAMbiguity** [comment] 2024-04-17 14:30
Duplicate of #204

**Closed as not planned by millennIumAMbiguity** 2024-04-17 14:30 UTC
Labels: duplicate

**Comment by Amzd** [comment] 2024-04-17 15:35
@millennIumAMbiguity Ah yea I didn't see that ticket, it is a duplicate, but that issue is tagged completed and had a linked PR? But the problem isn't fixed? Could you elaborate
