### ISSUE TITLE
Dissasembling ship 90° to the right of the original orientation causes ship-ruining block rotation

### ISSUE THREAD

**Issue by Ramelstag** [ValkyrienSkies/Eureka#271] opened 2023-10-27 22:08 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

### Issue description

Hi, I'm sure others have reported this issue, but just in case I'm reporting extra information about the issue which may not have been reported before.
For example, you assemble a ship that is facing north, and, you disassemble the ship when it is facing east, and east only, the ship will have it's fences, torches, stairs, and other blocks with rotation metadata rotated.
This can fortunately be fixed by doing the exact same thing again, re-assemble, and face south since the ship was facing east, and the blocks will rotate again, usually to their original rotation, fixing the damage, but I wouldn't count on it.
The same behavior can be found in the 1.18 and 1.19 versions.
Here's an example video: (instance in the video is 1.19.2 but the behavior is exactly the same in 1.20.1

https://imgur.com/a/apDm3fb

WORKAROUND IDEA: Make the mod remember which direction it was facing when assembled (possibly using the helm block's rotation metadata?), and, when the player hits the disassemble button, if possible, check if the current direction is 90° to the right of the original, and if it is, it tells the player that it cannot be disassembled to that direction, instead of disassembling. I have yet to become a competent programmer so I can't try this workaround idea myself unfortunately.

### Issue reproduction

1: Assemble ship
2: Rotate it 90° to the right (i.e, turn towards east if it was facing north when assembled)
3: Disassemble.
Doing it again can fix the damage done to the ship.

### Logs

[debug.log](https://github.com/ValkyrienSkies/Eureka/files/13193639/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Eureka/files/13193640/latest.log)

**Comment by PriestOfFern** [comment] 2023-10-28 12:03
Known issue, also 1.18 is the only really maintained version of VS2, with 1.19 and 1.20.1 only having been updated some months ago

**Comment by millennIumAMbiguity** [comment] 2024-04-17 17:30
Duplicate of #185

**Closed as not planned by millennIumAMbiguity** 2024-04-17 17:30 UTC
Labels: bug, duplicate
