### ISSUE TITLE
minecraft:pink_petals is not blacklisted by default

### ISSUE THREAD

**Issue by ghost** [ValkyrienSkies/Eureka#245] opened 2023-08-12 04:43 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.16

### Mod Loader

Forge

### Issue description

minecraft:pink_petals is not blacklisted by default

### Issue reproduction

minecraft:pink_petals is not blacklisted by default

**Comment by millennIumAMbiguity** [comment] 2023-08-13 10:48
duplicate of #229

also, [Pink Petals](https://minecraft.fandom.com/wiki/Pink_Petals) was added in Minecraft 1.20.

**Closed as completed** 2023-08-13 10:49 UTC
Labels: bug, Blacklist
