### ISSUE TITLE
Balloons, Helm... are still considered present when destroyed with explosions or fire.

### ISSUE THREAD

**Issue by Renzaccio** [ValkyrienSkies/Eureka#333] opened 2024-04-16 11:58 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [x] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Fabric

### Issue description

When a special block (balloon, helm...) are destroyed without the hand (with fire, tnt, fireball...), the ship don't behave like they have been destroyed.
For example if I destroy the helm of an airship with tnt, the ship don't fall, it stands like nothings happened.
Here is the video to illustrate : https://drive.google.com/file/d/1CqsurTP2436cfFudedIWs3A3lteE0urg/view?usp=sharing
It seems like the ballon and helm exist in a "ghost" state that allow the ship to float in the air.

I haven't tested it, but I suspect the same things would happens on floater and ballasts.
It is even possible that the general weight of the ship itself don't update when blocks are destroyed with explosions or fire.

I tested this issure on Fabric 1.20.1 with no other mods and on Quilt 1.20.1 with 50~100 other mods installed. It happened both times.

### Issue reproduction

- Create a ship with balloons
- lit fire or a tnt
- observe that when the helm and the balloon are destroyed the ship don't fall

For the ships to fall again, I had to quit/rejoin my world.

**Comment by millennIumAMbiguity** [comment] 2024-04-17 14:23
Duplicate of #308

**Closed as not planned by millennIumAMbiguity** 2024-04-17 14:23 UTC
Labels: bug, duplicate
